[develop] Carlos - Count most frequent item
AWT-05/coding pull request #5
Opened 2020-04-27 15:39 UTC by carlosmc23

2020-04-28 17:34 UTC, marcos-x86 requested changes
You are including `CalculateNumbers.java` and `HighestLowestTest.java` in your PR, your solutions were already merged, so please consider removing these two classes from your PR.

2020-04-28 17:34 UTC, marcos-x86 commented on src/main/java/org/fundacionjala/coding/carlos/countfrequentitem/CountFrequentItem.java
> +        for (int arrayNumber : arrayNumbers) {
Please consider removing duplicates from the original array first, according to your solution every number in the array will compute `verifyFrequency()` method including numbers already processed (the duplicated ones). Consider removing duplicates to improve performance with:
```java
LinkedHashSet<Integer> linkedHashSet = new LinkedHashSet<>(Arrays.asList(arrayNumbers));
Integer[] numbersWithoutDuplicates = linkedHashSet.toArray(new Integer[] {});
```

2020-04-28 17:34 UTC, marcos-x86 commented on src/main/java/org/fundacionjala/coding/carlos/countfrequentitem/CountFrequentItem.java
> +            if (repeated < verifyFrequency(number, arrayNumbers)) {
You are executing `verifyFrequency()` method two times, please consider store the result in a variable to reuse the value.
```java
int frequency = verifyFrequency(number, arrayNumbers);
if(repeated < frequency) {
  repeated = frecuency;
}
```

2020-04-30 04:31 UTC, carlosmc23 commented
Hi Marcos I found these ways to solve the exercise

- Set<Integer> linkedHashSet = new LinkedHashSet<>();  your suggestion
- list.stream().distinct().collect(Collectors.toList());
- Collections.frequency(aLista,s)

but I am using this and I think is a better way:

- map.merge(i, 1, Integer::sum);

Where merge is a method that searches if the key exists in your Map, if it does not exist it creates it with the value that you have passed to it (1), and if it exists it applies to the value that it already has a mapping with the value that you pass it ( in this case we sum 1 to the value that was previously associated)

2020-04-30 17:20 UTC, marcos-x86 approved these changes
LGTM!

2020-04-30 17:20 UTC, merged